// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package domain

type ListTag []Tag

func (list ListTag) AppendIfUnique(item Tag) ListTag {
	if list.Contains(item) == false {
		return append(list, item)
	}
	return list
}

func (list ListTag) Contains(item Tag) bool {
	for _, items := range list {
		if items == item {
			return true
		}
	}
	return false
}

func (list ListTag) Remove(items ...Tag) ListTag {
	newList := NewListTag()
	toRemove := NewListTag(items...)
	for _, existingItem := range list {
		if !toRemove.Contains(existingItem) {
			newList = append(newList, existingItem)
		}
	}
	return newList
}

func NewListTag(items ...Tag) ListTag {
	slice := make([]Tag, 0)
	for _, item := range items {
		slice = append(slice, item)
	}
	return slice
}
