// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package domain

type ListItem []Item

func (list ListItem) areSame(item1 Item, item2 Item) bool {
	return item1.URL == item2.URL
}

func NewListItem(items ...Item) ListItem {
	slice := make([]Item, 0)
	for _, item := range items {
		slice = append(slice, item)
	}
	return slice
}

//TODO - handle comparors
func (list ListItem) AppendIfUnique(item Item) ListItem {
	if list.Contains(item) == false {
		return append(list, item)
	}
	return list
}

func (list ListItem) Contains(item Item) bool {
	for _, listItem := range list {
		if list.areSame(listItem, item) {
			return true
		}
	}
	return false
}

func (list ListItem) Remove(items ...Item) ListItem {
	newList := NewListItem()
	toRemove := NewListItem(items...)
	for _, existingItem := range list {
		if !toRemove.Contains(existingItem) {
			newList = append(newList, existingItem)
		}
	}
	return newList
}

func (list ListItem) IndexOf(item Item) int {
	for index, existingItem := range list {
		if list.areSame(existingItem, item) {
			return index
		}
	}
	return -1
}
