// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package domain

type ListUserID []UserID

func (list ListUserID) AppendIfUnique(item UserID) ListUserID {
	if list.Contains(item) == false {
		return append(list, item)
	}
	return list
}

func (list ListUserID) Contains(item UserID) bool {
	for _, items := range list {
		if items == item {
			return true
		}
	}
	return false
}

func (list ListUserID) Remove(items ...UserID) ListUserID {
	newList := NewListUserID()
	toRemove := NewListUserID(items...)
	for _, existingItem := range list {
		if !toRemove.Contains(existingItem) {
			newList = append(newList, existingItem)
		}
	}
	return newList
}

func NewListUserID(items ...UserID) ListUserID {
	slice := make([]UserID, 0)
	for _, item := range items {
		slice = append(slice, item)
	}
	return slice
}
