// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package domain

type ListGalleryID []GalleryID

func (list ListGalleryID) AppendIfUnique(item GalleryID) ListGalleryID {
	if list.Contains(item) == false {
		return append(list, item)
	}
	return list
}

func (list ListGalleryID) Contains(item GalleryID) bool {
	for _, items := range list {
		if items == item {
			return true
		}
	}
	return false
}

func (list ListGalleryID) Remove(items ...GalleryID) ListGalleryID {
	newList := NewListGalleryID()
	toRemove := NewListGalleryID(items...)
	for _, existingItem := range list {
		if !toRemove.Contains(existingItem) {
			newList = append(newList, existingItem)
		}
	}
	return newList
}

func NewListGalleryID(items ...GalleryID) ListGalleryID {
	slice := make([]GalleryID, 0)
	for _, item := range items {
		slice = append(slice, item)
	}
	return slice
}
